<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DT-TECH-2D80" name="testCases.LoginVerification" tests="8" failures="1" timestamp="11 Apr 2018 07:03:41 GMT" time="157.745" errors="0">
  <testcase name="loginTest" time="20.700" classname="testCases.LoginVerification"/>
  <testcase name="loginTest" time="15.469" classname="testCases.LoginVerification">
    <failure type="java.lang.AssertionError" message="FAIL">
      <![CDATA[java.lang.AssertionError: FAILat org.testng.Assert.fail(Assert.java:96)at testKeywords.Keyword.executeKeywords(Keyword.java:193)at testCases.LoginVerification.loginTest(LoginVerification.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="20.630" classname="testCases.LoginVerification"/>
  <testcase name="loginTest" time="18.432" classname="testCases.LoginVerification"/>
  <testcase name="loginTest" time="20.574" classname="testCases.LoginVerification"/>
  <testcase name="loginTest" time="20.680" classname="testCases.LoginVerification"/>
  <testcase name="loginTest" time="20.661" classname="testCases.LoginVerification"/>
  <testcase name="loginTest" time="20.599" classname="testCases.LoginVerification"/>
</testsuite> <!-- testCases.LoginVerification -->
